In [1]:
import cv2
from keras.models import load_model
import numpy as np
import time
import random

model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
started = False
next_round = True
countdown = False
counter = 0
elapsed = 0
round_time = 0
message = ''

def get_prediction_string(prediction):
    result = None
    if (prediction[0][0])>0.9:
        result = "Paper"
    elif prediction [0][1]>0.9:
        result = 'Rock'
    elif prediction [0][2]>0.9:
        result = 'Scissors'
    return result

def winner(human, computer):
    message = ""
    if human == 'Rock':
        if computer == 'Rock':
            message += "It's a draw"
        elif computer == 'Paper':
            message += 'Sorry you lose'
        else: 
            message += 'Great , you WIN!'
    elif human == 'Paper':
        if computer == 'Rock':
            message += "Great , you WIN!"
        elif computer == 'Paper':
            message += "It's a draw"
        else: 
            message += 'Sorry you lose'
    elif human == 'Scissors':  
        if computer == 'Rock':
            message += 'Sorry you lose'
        elif computer == 'Paper':
            message += 'Great , you WIN!'
        else: 
            message += "It's a draw"
    else:
        message += 'Wrong prediction' 
    return message

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the imagekaras_model
    data[0] = normalized_image
    prediction = model.predict(data)
    print(prediction)
    if not started:
        message = 'Press a to strat'
    if cv2.waitKey(33) == ord ('a'):
        if not started:
            counter = time.time()
            started = True
            countdown = True
    if started:
        elapsed = 5 - (time.time() - counter)
        if elapsed <= -4:
            message = 'Press n to play the next round' 
            if cv2.waitKey(33) == ord ('n'):
                started = False
                elapsed = 0
        elif elapsed <= 0:
            countdown = False
            human = get_prediction_string(prediction)
            computer =  random.choice (['Rock','Paper','Scissors']) 
            message = f'You Showed {human}, and the computer showed {computer}.'
            winner(human, computer)     
        if countdown:
            message = f' Show yuor hand in  {int (elapsed)} seconds'

    cv2.putText(frame, message, (30,30), cv2.FONT_HERSHEY_SIMPLEX, 1,(0, 0, 255), 1)
    cv2.imshow('frame', frame)
    #press q to close the window
    if cv2.waitKey(1) & 0xFF == ord ('q'):
       break            

cv2.waitKey (1)
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


2022-03-20 16:40:12.281805: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[9.9999881e-01 1.1588074e-07 2.1759519e-08 1.0402794e-06]]
[[9.9999833e-01 7.1433260e-07 1.2726219e-08 9.8789360e-07]]
[[9.9996305e-01 1.6346365e-05 1.3149729e-08 2.0666479e-05]]
[[9.9999690e-01 3.0391086e-06 4.3769061e-11 9.2281631e-08]]
[[9.9999952e-01 4.5643361e-07 1.5927884e-11 2.5514211e-08]]
[[9.9999678e-01 2.2824515e-06 2.4220281e-09 8.9408763e-07]]
[[9.9999952e-01 3.1724755e-07 1.7151228e-09 1.5043075e-07]]
[[9.9999809e-01 5.1311685e-07 2.0195263e-09 1.3610818e-06]]
[[9.9999714e-01 2.4978847e-06 1.4405936e-09 3.3131903e-07]]
[[9.9999619e-01 3.3380250e-06 1.8122954e-09 4.8952796e-07]]
[[9.9999821e-01 1.3589653e-06 1.2467146e-09 4.2873418e-07]]
[[9.9999893e-01 6.7367887e-07 1.2292073e-09 4.3541422e-07]]
[[9.9999607e-01 1.5554020e-06 1.9821125e-09 2.4183719e-06]]
[[9.9999666e-01 1.7706986e-06 7.0060407e-10 1.5471080e-06]]
[[9.9999809e-01 1.4462412e-06 2.2816067e-09 5.1733610e-07]]
[[9.9999869e-01 1.3175633e-06 7.2519650e-11 1.2254200e-08]]
[[9.9999976e-01 2.8939107e-07 5.5021270e