In [1]:
import cv2
from keras.models import load_model
import numpy as np
import time
import random

model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
started = False
next_round = True
countdown = False
counter = 0
elapsed = 0
round_time = 0
message = ''

def get_prediction_string(prediction):
    result = None
    if (prediction[0][0])>0.9:
        result = "Paper"
    elif prediction [0][1]>0.9:
        result = 'Rock'
    elif prediction [0][2]>0.9:
        result = 'Scissors'
    return result

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the imagekaras_model
    data[0] = normalized_image
    prediction = model.predict(data)
    print(prediction)
    if not started:
        message = 'Press a to strat'
    if cv2.waitKey(33) == ord ('a'):
        if not started:
            counter = time.time()
            started = True
            countdown = True
    if started:
        elapsed = 5 - (time.time() - counter)
        if elapsed <= -4:
            message = 'Press n to play the next round' 
            if cv2.waitKey(33) == ord ('n'):
                started = False
                elapsed = 0
        elif elapsed <= 0:
            countdown = False
            #prediction ='Rock'
            prediction_string = get_prediction_string(prediction)
            computer =  random.choice (['Rock','Paper','Scissors']) 
            message = f'You Showed {prediction_string}, and the computer showed {computer}.'
            if prediction_string == 'Rock':
                if computer == 'Rock':
                    message += "It's a draw"
                elif computer == 'Paper':
                    message += 'Sorry you lose'
                else: 
                    message += 'Great , you WIN!'
            elif prediction_string == 'Paper':
                if computer == 'Rock':
                    message += "Great , you WIN!"
                elif computer == 'Paper':
                    message += "It's a draw"
                else: 
                    message += 'Sorry you lose'
            elif prediction_string == 'Scissors':  
                if computer == 'Rock':
                    message += 'Sorry you lose'
                elif computer == 'Paper':
                    message += 'Great , you WIN!'
                else: 
                    message += "It's a draw"
            else:
                message += 'Wrong prediction'          
        if countdown:
            message = f' Show yuor hand in  {int (elapsed)} seconds'

    cv2.putText(frame, message, (30,30), cv2.FONT_HERSHEY_SIMPLEX, 1,(0, 0, 255), 1)
    cv2.imshow('frame', frame)
    #press q to close the window
    if cv2.waitKey(1) & 0xFF == ord ('q'):
       break            
cv2.waitKey (1)
cv2.waitKey (1)
# After the loop release the cap object
cap.release()
cv2.waitKey(1000)

# Destroy all the windows
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

2022-03-15 14:57:26.026626: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[9.9975055e-01 1.4790318e-05 5.7016343e-09 2.3469314e-04]]
[[9.9946302e-01 8.4185813e-06 1.2290319e-08 5.2859134e-04]]
[[9.9939239e-01 1.2969762e-05 4.8635189e-09 5.9464312e-04]]
[[9.99774635e-01 1.50415135e-05 1.06125375e-09 2.10376820e-04]]
[[9.9707317e-01 2.3957668e-04 2.4808224e-09 2.6872251e-03]]
[[9.9740881e-01 4.2558234e-04 2.2389992e-09 2.1655830e-03]]
[[9.9820757e-01 2.4511787e-04 1.6402993e-09 1.5473536e-03]]
[[9.9264443e-01 1.4619802e-03 4.1814983e-09 5.8935084e-03]]
[[9.9643230e-01 2.9785556e-04 2.7928828e-09 3.2698796e-03]]
[[9.9599457e-01 1.9043390e-04 3.4068328e-09 3.8150251e-03]]
[[9.9761885e-01 3.7536860e-04 2.7294087e-09 2.0057859e-03]]
[[9.9939239e-01 8.5724852e-05 1.9413200e-09 5.2186556e-04]]
[[9.9908686e-01 1.6410911e-04 1.6754312e-09 7.4905361e-04]]
[[9.9865389e-01 2.3860126e-04 1.6857455e-09 1.1074332e-03]]
[[9.992895e-01 5.626688e-05 8.165452e-10 6.541807e-04]]
[[9.9828893e-01 1.7151251e-04 5.4804992e-09 1.5395146e-03]]
[[9.9924219e-01 1.4625399e-04 2.4952738e